project:
  type: website
  output-dir: docs

website:
  title: "Zaishan Weng"
  navbar:
    search: true
    collapse: true
    right:
      - text: "Home"
        href: about.qmd
      - text: "Blog"
        href: about.qmd
      - text: "Videos & Articles"
        href: about.qmd
      - icon: github
        href: https://github.com/ZS-Weng
      - icon: linkedin
        href: https://www.linkedin.com/in/zaishan-weng/

  page-footer:
    left: "© Copyright 2023 Zaishan Weng"
format:
  html:
    theme: 
      light: [cosmo, theme.scss]
    css: styles.css



