project:
  type: website
  output-dir: docs

website:
  title: "Zaishan Weng"
  site-url: 'https://zs-weng.github.io/blog/'
  description: "This is Zaishan Weng's personal website containing Data and AI related information."
  navbar:
    search: true
    collapse: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: data-ai-blog.qmd
      - text: "Videos & Articles"
        href: videos-articles.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/zaishan-weng/
      

  page-footer:
    left: 
      - "© Copyright 2023 Zaishan Weng"
    right:
      - icon: github
        href: https://github.com/ZS-Weng
      - icon: linkedin
        href: https://www.linkedin.com/in/zaishan-weng/
  
  google-analytics: 
    tracking-id: "G-8TTMHMV8LK"
    storage: none
  
format:
  html:
    theme: 
      light: [cosmo]
    css: styles.css

  



