project:
  type: website
  output-dir: docs

website:
  title: "Zaishan's Blog"
  navbar:
    search: true
    collapse: true
    right:
      - about.qmd
      - text: "Blog"
      - text: "Videos & Articles"
      - icon: github
        href: https://github.com/ZS-Weng
      - icon: linkedin
        href: https://www.linkedin.com/in/zaishan-weng/
format:
  html:
    theme: cosmo
    css: styles.css



