project:
  type: website
  output-dir: docs

website:
  title: "Zaishan Weng"
  description: "This is Zaishan's personal website."
  navbar:
    search: true
    collapse: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      

  page-footer:
    left: 
      - "© Copyright 2023 Zaishan Weng"
    right:
      - icon: github
        href: https://github.com/ZS-Weng
      - icon: linkedin
        href: https://www.linkedin.com/in/zaishan-weng/
format:
  html:
    theme: 
      light: [cosmo]
    css: styles.css



